package math;

public enum ShapeType {
    RECTANGLE,
    TRAPEZIUM1,
    TRAPEZIUM2,
    TRAPEZIUM3,
    TRAPEZIUM4,
    PENTAGON,
    PARALLELOGRAM1,
    PARALLELOGRAM2,
    PARALLELOGRAM3,
    PARALLELOGRAM4,
    REGULARTRAPEZIUMLEFT,
    REGULARTRAPEZIUMRIGHT;
}
