package math;

public enum ShapeType {
    RECTANGLE,
    TRAPEZIUM1,
    TRAPEZIUM2,
    TRAPEZIUM3,
    TRAPEZIUM4,
    PENTAGON,
    PARAlLELOGRAM1,
    PARALlELOGRAM2,
    REGULARTRAPEZIUMLEFT,
    REGULARTRAPEZIUMRIGHT;
}
